[features]
seeds = false
skip-lint = false
[programs.localnet]
code_vm = "vmZ1RZZyaskXS2fF668wonXFZiUDurcCr2eCev4kuuT"

[registry]
url = "https://api.apr.dev"

[provider]
wallet = "keypair-owner.json"
cluster = "http://127.0.0.1:8899"

[scripts]
test = "yarn run vitest run tests/vm.test.ts --testTimeout 25000 --bail 1"
